//
// THIS IS USED IN "DashboardHome" CARD
//
package Components;
import Utilities.*;

/**
 *
 * @author Admin
 */
public class DashboardExtras extends javax.swing.JPanel {

    /**
     * Creates new form DashboardExtras
     */
    public DashboardExtras() {
        initComponents();
        dashboardUserInfo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jobVacanciesPanel = new javax.swing.JPanel();
        announcementTitleBar = new javax.swing.JPanel();
        announcments = new javax.swing.JLabel();
        guides = new javax.swing.JPanel();
        GuidesTitleBar = new javax.swing.JPanel();
        guideLabel = new javax.swing.JLabel();
        remindersPanel = new javax.swing.JPanel();
        remindersTitleBar = new javax.swing.JPanel();
        reminders = new javax.swing.JLabel();
        reminder1_us = new javax.swing.JLabel();
        reminder1_ph = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        showUserInfo = new javax.swing.JButton();
        links_etc1 = new javax.swing.JPanel();
        linksTitleBar1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dashboardUserInfo = new Components.DashboardUserInfo();
        announcementsPanel1 = new javax.swing.JPanel();
        announcementTitleBar1 = new javax.swing.JPanel();
        announcments1 = new javax.swing.JLabel();

        setBackground(ThemeColors.BACKGROUND);

        jobVacanciesPanel.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        announcementTitleBar.setBackground(ThemeColors.SURFACE_VARIANT);
        announcementTitleBar.setForeground(new java.awt.Color(255, 255, 255));

        announcments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        announcments.setForeground(ThemeColors.ON_SURFACE);
        announcments.setText("Job Vacancies");

        javax.swing.GroupLayout announcementTitleBarLayout = new javax.swing.GroupLayout(announcementTitleBar);
        announcementTitleBar.setLayout(announcementTitleBarLayout);
        announcementTitleBarLayout.setHorizontalGroup(
            announcementTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementTitleBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(announcments)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        announcementTitleBarLayout.setVerticalGroup(
            announcementTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(announcments)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jobVacanciesPanelLayout = new javax.swing.GroupLayout(jobVacanciesPanel);
        jobVacanciesPanel.setLayout(jobVacanciesPanelLayout);
        jobVacanciesPanelLayout.setHorizontalGroup(
            jobVacanciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(announcementTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jobVacanciesPanelLayout.setVerticalGroup(
            jobVacanciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobVacanciesPanelLayout.createSequentialGroup()
                .addComponent(announcementTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 529, Short.MAX_VALUE))
        );

        guides.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        GuidesTitleBar.setBackground(ThemeColors.SURFACE_VARIANT);
        GuidesTitleBar.setForeground(new java.awt.Color(255, 255, 255));

        guideLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        guideLabel.setForeground(ThemeColors.ON_SURFACE);
        guideLabel.setText("Guides");

        javax.swing.GroupLayout GuidesTitleBarLayout = new javax.swing.GroupLayout(GuidesTitleBar);
        GuidesTitleBar.setLayout(GuidesTitleBarLayout);
        GuidesTitleBarLayout.setHorizontalGroup(
            GuidesTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuidesTitleBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(guideLabel)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        GuidesTitleBarLayout.setVerticalGroup(
            GuidesTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuidesTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guideLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout guidesLayout = new javax.swing.GroupLayout(guides);
        guides.setLayout(guidesLayout);
        guidesLayout.setHorizontalGroup(
            guidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuidesTitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        guidesLayout.setVerticalGroup(
            guidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guidesLayout.createSequentialGroup()
                .addComponent(GuidesTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 351, Short.MAX_VALUE))
        );

        remindersPanel.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        remindersTitleBar.setBackground(ThemeColors.SURFACE_VARIANT);
        remindersTitleBar.setForeground(new java.awt.Color(255, 255, 255));

        reminders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reminders.setForeground(ThemeColors.ON_SURFACE);
        reminders.setText("Reminders");

        javax.swing.GroupLayout remindersTitleBarLayout = new javax.swing.GroupLayout(remindersTitleBar);
        remindersTitleBar.setLayout(remindersTitleBarLayout);
        remindersTitleBarLayout.setHorizontalGroup(
            remindersTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersTitleBarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(reminders)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        remindersTitleBarLayout.setVerticalGroup(
            remindersTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reminders)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reminder1_us.setBackground(ThemeColors.ON_SURFACE);
        reminder1_us.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reminder1_us.setForeground(ThemeColors.ON_SURFACE);
        reminder1_us.setText("Make sure all your information is correct and true because it will all be saved for processing ");

        reminder1_ph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reminder1_ph.setForeground(ThemeColors.ON_SURFACE);
        reminder1_ph.setText("Siguraduhin na ang lahat ng iyong impormasyon ay tama at totoo dahil ang lahat ng ito ay ise-save para sa pagproseso");

        javax.swing.GroupLayout remindersPanelLayout = new javax.swing.GroupLayout(remindersPanel);
        remindersPanel.setLayout(remindersPanelLayout);
        remindersPanelLayout.setHorizontalGroup(
            remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(remindersTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(remindersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reminder1_us)
                    .addComponent(reminder1_ph))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        remindersPanelLayout.setVerticalGroup(
            remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersPanelLayout.createSequentialGroup()
                .addComponent(remindersTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reminder1_us)
                .addGap(14, 14, 14)
                .addComponent(reminder1_ph)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        jPanel1.setBackground(ThemeColors.BACKGROUND);

        showUserInfo.setBackground(ThemeColors.PRIMARY);
        showUserInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showUserInfo.setForeground(ThemeColors.ON_PRIMARY);
        showUserInfo.setText("Show User Information");
        showUserInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUserInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(showUserInfo)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        links_etc1.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        linksTitleBar1.setBackground(ThemeColors.SURFACE_VARIANT);
        linksTitleBar1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(ThemeColors.ON_SURFACE);
        jLabel6.setText("Links");

        javax.swing.GroupLayout linksTitleBar1Layout = new javax.swing.GroupLayout(linksTitleBar1);
        linksTitleBar1.setLayout(linksTitleBar1Layout);
        linksTitleBar1Layout.setHorizontalGroup(
            linksTitleBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksTitleBar1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        linksTitleBar1Layout.setVerticalGroup(
            linksTitleBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksTitleBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout links_etc1Layout = new javax.swing.GroupLayout(links_etc1);
        links_etc1.setLayout(links_etc1Layout);
        links_etc1Layout.setHorizontalGroup(
            links_etc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linksTitleBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        links_etc1Layout.setVerticalGroup(
            links_etc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(links_etc1Layout.createSequentialGroup()
                .addComponent(linksTitleBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 318, Short.MAX_VALUE))
        );

        announcementsPanel1.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        announcementTitleBar1.setBackground(ThemeColors.SURFACE_VARIANT);
        announcementTitleBar1.setForeground(new java.awt.Color(255, 255, 255));

        announcments1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        announcments1.setForeground(ThemeColors.ON_SURFACE);
        announcments1.setText("Announcements");

        javax.swing.GroupLayout announcementTitleBar1Layout = new javax.swing.GroupLayout(announcementTitleBar1);
        announcementTitleBar1.setLayout(announcementTitleBar1Layout);
        announcementTitleBar1Layout.setHorizontalGroup(
            announcementTitleBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementTitleBar1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(announcments1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        announcementTitleBar1Layout.setVerticalGroup(
            announcementTitleBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementTitleBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(announcments1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout announcementsPanel1Layout = new javax.swing.GroupLayout(announcementsPanel1);
        announcementsPanel1.setLayout(announcementsPanel1Layout);
        announcementsPanel1Layout.setHorizontalGroup(
            announcementsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(announcementTitleBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        announcementsPanel1Layout.setVerticalGroup(
            announcementsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementsPanel1Layout.createSequentialGroup()
                .addComponent(announcementTitleBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 529, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(announcementsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jobVacanciesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(remindersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guides, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(links_etc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(links_etc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remindersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(announcementsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobVacanciesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dashboardUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void showUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUserInfoActionPerformed
        // TODO add your handling code here:
        if (dashboardUserInfo.isVisible()) {
            dashboardUserInfo.setVisible(false);
            showUserInfo.setText("Show User Information");
        } else {
            dashboardUserInfo.setVisible(true);
            showUserInfo.setText("Hide User Information");
        }
    }//GEN-LAST:event_showUserInfoActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GuidesTitleBar;
    private javax.swing.JPanel announcementTitleBar;
    private javax.swing.JPanel announcementTitleBar1;
    private javax.swing.JPanel announcementsPanel1;
    private javax.swing.JLabel announcments;
    private javax.swing.JLabel announcments1;
    private Components.DashboardUserInfo dashboardUserInfo;
    private javax.swing.JLabel guideLabel;
    private javax.swing.JPanel guides;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jobVacanciesPanel;
    private javax.swing.JPanel linksTitleBar1;
    private javax.swing.JPanel links_etc1;
    private javax.swing.JLabel reminder1_ph;
    private javax.swing.JLabel reminder1_us;
    private javax.swing.JLabel reminders;
    private javax.swing.JPanel remindersPanel;
    private javax.swing.JPanel remindersTitleBar;
    private javax.swing.JButton showUserInfo;
    // End of variables declaration//GEN-END:variables
}
