//
// THIS IS USED IN "DashboardHome" CARD
//
package Components;
import Utilities.*;

/**
 *
 * @author Admin
 */
public class DashboardExtras extends javax.swing.JPanel {

    /**
     * Creates new form DashboardExtras
     */
    public DashboardExtras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePicturePanel = new javax.swing.JPanel();
        profilePictureIMG = new javax.swing.JLabel();
        passportPicturePanel = new javax.swing.JPanel();
        passportPictureIMG = new javax.swing.JLabel();
        attachPassport = new javax.swing.JButton();
        attachProfile = new javax.swing.JButton();
        announcementsPanel = new javax.swing.JPanel();
        announcementTitleBar = new javax.swing.JPanel();
        announcments = new javax.swing.JLabel();
        links_etc = new javax.swing.JPanel();
        linksTitleBar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        remindersPanel = new javax.swing.JPanel();
        remindersTitleBar = new javax.swing.JPanel();
        reminders = new javax.swing.JLabel();
        reminder1_ph_2 = new javax.swing.JLabel();
        reminder1_us = new javax.swing.JLabel();
        reminder1_ph = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userDetails = new javax.swing.JPanel();
        accountNumber = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();

        setBackground(ThemeColors.BACKGROUND);

        profilePicturePanel.setBackground(ThemeColors.ON_SURFACE);
        profilePicturePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        profilePicturePanel.setPreferredSize(new java.awt.Dimension(165, 165));

        profilePictureIMG.setText("profile picture");

        javax.swing.GroupLayout profilePicturePanelLayout = new javax.swing.GroupLayout(profilePicturePanel);
        profilePicturePanel.setLayout(profilePicturePanelLayout);
        profilePicturePanelLayout.setHorizontalGroup(
            profilePicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePicturePanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(profilePictureIMG)
                .addGap(44, 44, 44))
        );
        profilePicturePanelLayout.setVerticalGroup(
            profilePicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePicturePanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(profilePictureIMG)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        passportPicturePanel.setBackground(ThemeColors.ON_SURFACE);
        passportPicturePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        passportPicturePanel.setPreferredSize(new java.awt.Dimension(165, 165));

        passportPictureIMG.setText("passport picture");

        javax.swing.GroupLayout passportPicturePanelLayout = new javax.swing.GroupLayout(passportPicturePanel);
        passportPicturePanel.setLayout(passportPicturePanelLayout);
        passportPicturePanelLayout.setHorizontalGroup(
            passportPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passportPicturePanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(passportPictureIMG)
                .addGap(36, 36, 36))
        );
        passportPicturePanelLayout.setVerticalGroup(
            passportPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passportPicturePanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(passportPictureIMG)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        attachPassport.setBackground(ThemeColors.PRIMARY);
        attachPassport.setForeground(ThemeColors.ON_PRIMARY);
        attachPassport.setText("Attach Picture");
        attachPassport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attachPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachPassportActionPerformed(evt);
            }
        });

        attachProfile.setBackground(ThemeColors.PRIMARY);
        attachProfile.setForeground(ThemeColors.ON_PRIMARY);
        attachProfile.setText("Attach Picture");
        attachProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attachProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachProfileActionPerformed(evt);
            }
        });

        announcementsPanel.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        announcementTitleBar.setBackground(ThemeColors.SURFACE_VARIANT);
        announcementTitleBar.setForeground(new java.awt.Color(255, 255, 255));

        announcments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        announcments.setForeground(ThemeColors.ON_SURFACE);
        announcments.setText("Announcements");

        javax.swing.GroupLayout announcementTitleBarLayout = new javax.swing.GroupLayout(announcementTitleBar);
        announcementTitleBar.setLayout(announcementTitleBarLayout);
        announcementTitleBarLayout.setHorizontalGroup(
            announcementTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementTitleBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(announcments)
                .addContainerGap(445, Short.MAX_VALUE))
        );
        announcementTitleBarLayout.setVerticalGroup(
            announcementTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(announcments)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(announcementTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        announcementsPanelLayout.setVerticalGroup(
            announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(announcementsPanelLayout.createSequentialGroup()
                .addComponent(announcementTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        links_etc.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        linksTitleBar.setBackground(ThemeColors.SURFACE_VARIANT);
        linksTitleBar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(ThemeColors.ON_SURFACE);
        jLabel5.setText("Links");

        javax.swing.GroupLayout linksTitleBarLayout = new javax.swing.GroupLayout(linksTitleBar);
        linksTitleBar.setLayout(linksTitleBarLayout);
        linksTitleBarLayout.setHorizontalGroup(
            linksTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksTitleBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        linksTitleBarLayout.setVerticalGroup(
            linksTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout links_etcLayout = new javax.swing.GroupLayout(links_etc);
        links_etc.setLayout(links_etcLayout);
        links_etcLayout.setHorizontalGroup(
            links_etcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linksTitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        links_etcLayout.setVerticalGroup(
            links_etcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(links_etcLayout.createSequentialGroup()
                .addComponent(linksTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        remindersPanel.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        remindersTitleBar.setBackground(ThemeColors.SURFACE_VARIANT);
        remindersTitleBar.setForeground(new java.awt.Color(255, 255, 255));

        reminders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reminders.setForeground(ThemeColors.ON_SURFACE);
        reminders.setText("Reminders");

        javax.swing.GroupLayout remindersTitleBarLayout = new javax.swing.GroupLayout(remindersTitleBar);
        remindersTitleBar.setLayout(remindersTitleBarLayout);
        remindersTitleBarLayout.setHorizontalGroup(
            remindersTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersTitleBarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(reminders)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        remindersTitleBarLayout.setVerticalGroup(
            remindersTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reminders)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reminder1_ph_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reminder1_ph_2.setForeground(ThemeColors.ON_SURFACE);
        reminder1_ph_2.setText("ise-save para sa pagproseso");

        reminder1_us.setBackground(ThemeColors.ON_SURFACE);
        reminder1_us.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reminder1_us.setForeground(ThemeColors.ON_SURFACE);
        reminder1_us.setText("Make sure all your information is correct and true because it will all be saved for processing ");

        reminder1_ph.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reminder1_ph.setForeground(ThemeColors.ON_SURFACE);
        reminder1_ph.setText("Siguraduhin na ang lahat ng iyong impormasyon ay tama at totoo dahil ang lahat ng ito ay");

        jSeparator1.setForeground(ThemeColors.ON_SURFACE_VARIANT);

        javax.swing.GroupLayout remindersPanelLayout = new javax.swing.GroupLayout(remindersPanel);
        remindersPanel.setLayout(remindersPanelLayout);
        remindersPanelLayout.setHorizontalGroup(
            remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(remindersTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(remindersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reminder1_us)
                    .addComponent(reminder1_ph_2)
                    .addComponent(reminder1_ph))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        remindersPanelLayout.setVerticalGroup(
            remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersPanelLayout.createSequentialGroup()
                .addComponent(remindersTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reminder1_us)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reminder1_ph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reminder1_ph_2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        userDetails.setOpaque(false);

        accountNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountNumber.setForeground(ThemeColors.ON_BACKGROUND);
        accountNumber.setText("Account no.");

        userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName.setForeground(ThemeColors.ON_BACKGROUND);
        userName.setText("Lastname, Firstname MI.");

        javax.swing.GroupLayout userDetailsLayout = new javax.swing.GroupLayout(userDetails);
        userDetails.setLayout(userDetailsLayout);
        userDetailsLayout.setHorizontalGroup(
            userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountNumber)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userDetailsLayout.setVerticalGroup(
            userDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(attachPassport))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(passportPicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profilePicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(attachProfile))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remindersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(links_etc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(links_etc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(profilePicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attachProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(remindersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passportPicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attachPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void attachPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachPassportActionPerformed
        // replace jlabel "passportPictureIMG" with passport picture
    }//GEN-LAST:event_attachPassportActionPerformed

    private void attachProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachProfileActionPerformed
        // replace jlabel "profilePictureIMG" with profile picure
    }//GEN-LAST:event_attachProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JPanel announcementTitleBar;
    private javax.swing.JPanel announcementsPanel;
    private javax.swing.JLabel announcments;
    private javax.swing.JButton attachPassport;
    private javax.swing.JButton attachProfile;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel linksTitleBar;
    private javax.swing.JPanel links_etc;
    private javax.swing.JLabel passportPictureIMG;
    private javax.swing.JPanel passportPicturePanel;
    private javax.swing.JLabel profilePictureIMG;
    private javax.swing.JPanel profilePicturePanel;
    private javax.swing.JLabel reminder1_ph;
    private javax.swing.JLabel reminder1_ph_2;
    private javax.swing.JLabel reminder1_us;
    private javax.swing.JLabel reminders;
    private javax.swing.JPanel remindersPanel;
    private javax.swing.JPanel remindersTitleBar;
    private javax.swing.JPanel userDetails;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
