/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Cards;

/**
 *
 * @author napbo
 */

import API.Auth;
import API.SQLHandler;
import Components.*;
import Components.TableComponents.EducationTable;
import Utilities.*;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Map;

public class MyEducation extends javax.swing.JPanel {

    /**
     * Creates new form DashBoardF11
     */
    public MyEducation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AddEducation = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        educationTable1 = new Components.TableComponents.EducationTable();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel3.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);

        AddEducation.setBackground(ThemeColors.PRIMARY);
        AddEducation.setForeground(ThemeColors.ON_PRIMARY);
        AddEducation.setText("Add Education");
        AddEducation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEducationMouseClicked(evt);
            }
        });
        AddEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEducationActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(ThemeColors.ON_SURFACE);
        jLabel3.setText("Education");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 798, Short.MAX_VALUE)
                .addComponent(AddEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 5, 0));
        jPanel2.add(educationTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEducationActionPerformed

    private void AddEducationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEducationMouseClicked
        // TODO add your handling code here:
        Education_FORM education = new Education_FORM();
        education.setVisible(true);
        education.pack();
        education.setLocationRelativeTo(null);
        education.setAlwaysOnTop(false);
        education.setResizable(false);
        education.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_AddEducationMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEducation;
    private Components.TableComponents.EducationTable educationTable1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    // At element load, populate the tables with the data from the database
    @Override
    public void addNotify() {
        super.addNotify();
        //Populate the tables with the data from the database
        EducationTable.updateTable();
    }
}
