/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Cards;

import Components.AddExperienceWindow;
import Components.TableComponents.ExperienceTable;
import Components.TableComponents.TrainingTable;
import Utilities.*;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class MyExperience extends javax.swing.JPanel {

    /**
     * Creates new form MyExperience
     */
    public MyExperience() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        workExperienceTitleBar = new javax.swing.JPanel();
        workExperienceLabel = new javax.swing.JLabel();
        addExperienceButton = new javax.swing.JButton();
        experiencePanel1 = new Components.TableComponents.ExperienceTable();

        setBackground(ThemeColors.BACKGROUND);

        workExperienceTitleBar.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);
        workExperienceTitleBar.setForeground(ThemeColors.ON_SURFACE);
        workExperienceTitleBar.setPreferredSize(new java.awt.Dimension(690, 58));

        workExperienceLabel.setBackground(ThemeColors.ON_PRIMARY_CONTAINER);
        workExperienceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        workExperienceLabel.setForeground(ThemeColors.ON_SURFACE);
        workExperienceLabel.setText("Work Experience");

        addExperienceButton.setBackground(ThemeColors.PRIMARY);
        addExperienceButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addExperienceButton.setForeground(ThemeColors.ON_PRIMARY);
        addExperienceButton.setText("Add Experience");
        addExperienceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addExperienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExperienceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workExperienceTitleBarLayout = new javax.swing.GroupLayout(workExperienceTitleBar);
        workExperienceTitleBar.setLayout(workExperienceTitleBarLayout);
        workExperienceTitleBarLayout.setHorizontalGroup(
            workExperienceTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workExperienceTitleBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(workExperienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addExperienceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        workExperienceTitleBarLayout.setVerticalGroup(
            workExperienceTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workExperienceTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workExperienceTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workExperienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExperienceButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        experiencePanel1.setBackground(ThemeColors.BACKGROUND);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(experiencePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
            .addComponent(workExperienceTitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(workExperienceTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(experiencePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addExperienceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExperienceButtonActionPerformed
        // Open AddExperienceWindow
        AddExperienceWindow addExp = new AddExperienceWindow();
        addExp.setVisible(true);
        addExp.pack();
        addExp.setLocationRelativeTo(null);
        addExp.setAlwaysOnTop(false);
        addExp.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_addExperienceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExperienceButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private Components.TableComponents.ExperienceTable experiencePanel1;
    private javax.swing.JLabel workExperienceLabel;
    private javax.swing.JPanel workExperienceTitleBar;
    // End of variables declaration//GEN-END:variables

    // At element load, populate the tables with the data from the database
    @Override
    public void addNotify() {
        super.addNotify();
        //Populate the tables with the data from the database
        ExperienceTable.updateTable();
    }
}
