/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Cards;

import Utilities.*;
/**
 *
 * @author Admin
 */
public class MyExperience extends javax.swing.JPanel {

    /**
     * Creates new form MyExperience
     */
    public MyExperience() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workExperienceTitleBar = new javax.swing.JPanel();
        workExperienceLabel = new javax.swing.JLabel();
        addExperienceButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        experiencePanel2 = new Components.ExperiencePanel();

        setBackground(ThemeColors.BACKGROUND);

        workExperienceTitleBar.setBackground(ThemeColors.SURFACE_CONTAINER_HIGH);
        workExperienceTitleBar.setForeground(ThemeColors.ON_SURFACE);

        workExperienceLabel.setBackground(ThemeColors.ON_PRIMARY_CONTAINER);
        workExperienceLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        workExperienceLabel.setForeground(ThemeColors.ON_SURFACE);
        workExperienceLabel.setText("Work Experience");

        addExperienceButton.setBackground(ThemeColors.PRIMARY);
        addExperienceButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addExperienceButton.setForeground(ThemeColors.ON_PRIMARY);
        addExperienceButton.setText("Add Experience");
        addExperienceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addExperienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExperienceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workExperienceTitleBarLayout = new javax.swing.GroupLayout(workExperienceTitleBar);
        workExperienceTitleBar.setLayout(workExperienceTitleBarLayout);
        workExperienceTitleBarLayout.setHorizontalGroup(
            workExperienceTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workExperienceTitleBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(workExperienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addComponent(addExperienceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        workExperienceTitleBarLayout.setVerticalGroup(
            workExperienceTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workExperienceTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workExperienceTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workExperienceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(addExperienceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setBackground(ThemeColors.SURFACE);
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(ThemeColors.ON_BACKGROUND);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(experiencePanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(workExperienceTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workExperienceTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addExperienceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExperienceButtonActionPerformed
        // Open AddExperience card
        
    }//GEN-LAST:event_addExperienceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExperienceButton;
    private Components.ExperiencePanel experiencePanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel workExperienceLabel;
    private javax.swing.JPanel workExperienceTitleBar;
    // End of variables declaration//GEN-END:variables
}
